# Generated by Django 2.2.16 on 2022-01-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='cgt.Categorie', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(help_text='Выберите жанр произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='cgt.Genre', verbose_name='Жанр'),
        ),
    ]
