# Generated by Django 2.2.16 on 2022-01-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgt', '0002_auto_20220117_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
