# Generated by Django 2.2.16 on 2021-12-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211229_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Moderator', 'Moderator')], default='User', max_length=25),
        ),
    ]
