# Generated by Django 2.2.16 on 2022-01-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220101_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'user'), ('Admin', 'admin'), ('Moderator', 'moderator')], default='User', max_length=25),
        ),
    ]
